enum PoseGuideCatalog {
    static let all: [PoseGuide] = [
        PoseGuide(
            id: "solo_side_stand",
            titleKey: "camera.pose.guide.solo_side_stand.title",
            shortHintKey: "camera.pose.guide.solo_side_stand.hint",
            category: .solo,
            assetName: "pose_solo_side_stand",
            framingHint: .fullBody,
            defaultScale: 0.86,
            defaultOffsetNormX: -0.02,
            defaultOffsetNormY: 0.01,
            defaultOpacity: 0.5,
            anchor: .bottomCenter,
            supportsMirroring: true,
            isPremium: false
        ),
        PoseGuide(
            id: "solo_walk",
            titleKey: "camera.pose.guide.solo_walk.title",
            shortHintKey: "camera.pose.guide.solo_walk.hint",
            category: .street,
            assetName: "pose_solo_walk",
            framingHint: .fullBody,
            defaultScale: 0.88,
            defaultOffsetNormX: 0.0,
            defaultOffsetNormY: 0.01,
            defaultOpacity: 0.5,
            anchor: .bottomCenter,
            supportsMirroring: true,
            isPremium: false
        ),
        PoseGuide(
            id: "half_body_turn_back",
            titleKey: "camera.pose.guide.half_body_turn_back.title",
            shortHintKey: "camera.pose.guide.half_body_turn_back.hint",
            category: .halfBody,
            assetName: "pose_half_body_turn_back",
            framingHint: .halfBody,
            defaultScale: 0.82,
            defaultOffsetNormX: 0.0,
            defaultOffsetNormY: -0.02,
            defaultOpacity: 0.5,
            anchor: .center,
            supportsMirroring: true,
            isPremium: false
        ),
        PoseGuide(
            id: "couple_side_by_side",
            titleKey: "camera.pose.guide.couple_side_by_side.title",
            shortHintKey: "camera.pose.guide.couple_side_by_side.hint",
            category: .couple,
            assetName: "pose_couple_side_by_side",
            framingHint: .fullBody,
            defaultScale: 0.86,
            defaultOffsetNormX: 0.0,
            defaultOffsetNormY: 0.01,
            defaultOpacity: 0.5,
            anchor: .bottomCenter,
            supportsMirroring: true,
            isPremium: false
        ),
        PoseGuide(
            id: "couple_staggered",
            titleKey: "camera.pose.guide.couple_staggered.title",
            shortHintKey: "camera.pose.guide.couple_staggered.hint",
            category: .couple,
            assetName: "pose_couple_staggered",
            framingHint: .fullBody,
            defaultScale: 0.86,
            defaultOffsetNormX: 0.0,
            defaultOffsetNormY: 0.0,
            defaultOpacity: 0.5,
            anchor: .bottomCenter,
            supportsMirroring: true,
            isPremium: false
        ),
        PoseGuide(
            id: "menswear_wall_lean",
            titleKey: "camera.pose.guide.menswear_wall_lean.title",
            shortHintKey: "camera.pose.guide.menswear_wall_lean.hint",
            category: .menswear,
            assetName: "pose_menswear_wall_lean",
            framingHint: .fullBody,
            defaultScale: 0.86,
            defaultOffsetNormX: 0.03,
            defaultOffsetNormY: 0.01,
            defaultOpacity: 0.5,
            anchor: .bottomCenter,
            supportsMirroring: true,
            isPremium: false
        ),
        PoseGuide(
            id: "womenswear_hair_touch",
            titleKey: "camera.pose.guide.womenswear_hair_touch.title",
            shortHintKey: "camera.pose.guide.womenswear_hair_touch.hint",
            category: .womenswear,
            assetName: "pose_womenswear_hair_touch",
            framingHint: .threeQuarter,
            defaultScale: 0.84,
            defaultOffsetNormX: -0.01,
            defaultOffsetNormY: 0.0,
            defaultOpacity: 0.5,
            anchor: .bottomCenter,
            supportsMirroring: true,
            isPremium: false
        ),
        PoseGuide(
            id: "seated_side_pose",
            titleKey: "camera.pose.guide.seated_side_pose.title",
            shortHintKey: "camera.pose.guide.seated_side_pose.hint",
            category: .seated,
            assetName: "pose_seated_side_pose",
            framingHint: .seated,
            defaultScale: 0.82,
            defaultOffsetNormX: 0.02,
            defaultOffsetNormY: 0.02,
            defaultOpacity: 0.5,
            anchor: .bottomCenter,
            supportsMirroring: true,
            isPremium: false
        )
    ]
}
